
inline const char* AllItemName[] =
{
"2DQuantumWafer",
"AdamCostume_001",
"AdamCostume_002",
"AdamCostume_003",
"AdamCostume_003_Var2",
"AdamCostume_004",
"AdamCostume_004_Var2",
"AdamCostume_Buffer1",
"AdamCostume_Buffer2",
"AdamCostume_Buffer3",
"AdamCostume_Christmas_01",
"AdamCostume_Nier_001",
"BetaCore",
"BodyCore",
"BS_01",
"BS_01_Var2",
"BS_01_Var3",
"BS_02",
"BS_02_Var2",
"BS_03",
"BS_03_Var2",
"BS_04",
"BS_04_Var2",
"BS_05",
"BS_05_Var2",
"BS_06",
"BS_07",
"BS_07_Var2",
"BS_08",
"BS_08_Var2",
"BS_09",
"BS_09_2",
"BS_10",
"BS_1000",
"BS_101",
"BS_102",
"BS_102_1",
"BS_11",
"BS_13",
"BS_13_Var2",
"BS_14",
"BS_14_Var2",
"BS_15",
"BS_15_Var2",
"BS_16",
"BS_16_Var2",
"BS_16_Var3",
"BS_17",
"BS_18",
"BS_19",
"BS_19_Var2",
"BS_20",
"BS_20_Var2",
"BS_21",
"BS_22",
"BS_22_Var2",
"BS_23",
"BS_23_Var2",
"BS_24",
"BS_24_Var2",
"BS_25",
"BS_26",
"BS_27",
"BS_28",
"BS_29",
"BS_30",
"BS_30_Var2",
"BS_31",
"BS_31_Var2",
"BS_32",
"BS_33",
"BS_34",
"BS_34_Var2",
"BS_35",
"BS_36",
"BS_37",
"BS_37_Var2",
"BS_37_Var3",
"BS_38",
"BS_38_Var2",
"BS_39",
"BS_40",
"BS_40_Var2",
"BS_40_Var3",
"BS_40_Var4",
"BS_41",
"BS_41_Var2",
"BS_42",
"BS_42_Var2",
"BS_43",
"BS_44",
"BS_44_Var2",
"BS_44_Var3",
"BS_45",
"BS_45_Var2",
"BS_46",
"BS_47",
"BS_47_Var2",
"BS_48",
"BS_48_Var2",
"BS_50",
"BS_52",
"BS_53",
"BS_54",
"BS_55",
"BS_56",
"BS_57",
"BS_99",
"BS_Bear",
"BS_Bear_Var2",
"BS_Black_Leather_bikini",
"BS_Black_Leather_bikini_Var2",
"BS_Blue_Suit",
"BS_Blue_Suit_Var2",
"BS_Buffer1",
"BS_Buffer10",
"BS_Buffer11",
"BS_Buffer12",
"BS_Buffer13",
"BS_Buffer14",
"BS_Buffer15",
"BS_Buffer2",
"BS_Buffer3",
"BS_Buffer4",
"BS_Buffer5",
"BS_Buffer6",
"BS_Buffer7",
"BS_Buffer8",
"BS_Buffer9",
"BS_Christmas_01",
"BS_Default",
"BS_Default_Var2",
"BS_Default_Var3",
"BS_EVE_04",
"BS_EVE_04_Var2",
"BS_Green_Suit",
"BS_Leather_Jean",
"BS_Leather_Jean_Var2",
"BS_Leather_Jean2",
"BS_Nier_01",
"BS_Nier_02",
"BS_Nier_03",
"BS_Nier_04",
"BS_Nikke_01",
"BS_Nikke_02",
"BS_Nikke_03",
"BS_Nikke_04",
"BS_Nikke_05",
"BS_Nikke_06",
"BS_Raven",
"BS_RoyalGuard_01",
"BS_Sailor_Jean",
"BS_Sailor_Jean_Var2",
"BS_SilverKunoichi",
"BS_White_Jean",
"BS_White_Jean_Var2",
"BS_Yellow_Suit",
"BS_Yellow_Suit_Jacket",
"BS_Yellow_Suit_Jacket_Var2",
"BS_Yellow_Suit_Var2",
"Buff_HP2MP",
"Bullet_Explosive",
"Bullet_Missile",
"Bullet_Normal",
"Bullet_Railgun",
"Bullet_Scatter",
"Bullet_Shock",
"BuyAllAmmo",
"Camera",
"Can_001",
"Can_002",
"Can_003",
"Can_004",
"Can_005",
"Can_006",
"Can_007",
"Can_008",
"Can_009",
"Can_010",
"Can_011",
"Can_012",
"Can_013",
"Can_014",
"Can_015",
"Can_016",
"Can_017",
"Can_018",
"Can_019",
"Can_020",
"Can_021",
"Can_022",
"Can_023",
"Can_024",
"Can_025",
"Can_026",
"Can_027",
"Can_028",
"Can_029",
"Can_030",
"Can_031",
"Can_032",
"Can_033",
"Can_034",
"Can_035",
"Can_036",
"Can_037",
"Can_038",
"Can_039",
"Can_040",
"Can_041",
"Can_042",
"Can_043",
"Can_044",
"Can_045",
"Can_046",
"Can_047",
"Can_048",
"Can_049",
"ConcussionGrenade",
"DesignPattern_Default",
"DroneCore",
"DroneSeal_001",
"DroneSeal_002",
"DroneSeal_002_Var2",
"DroneSeal_003",
"DroneSeal_004",
"DroneSeal_004_Var2",
"DroneSeal_005",
"DroneSeal_Buffer1",
"DroneSeal_Buffer2",
"DroneSeal_Buffer3",
"DroneSeal_Christmas_01",
"DroneSeal_Nier_001",
"Earring_001",
"Earring_001_Var2",
"Earring_002",
"Earring_002_Var2",
"Earring_003",
"Earring_003_Var2",
"Earring_004",
"Earring_005",
"Earring_006",
"Earring_007",
"Earring_008",
"Earring_008_Var2",
"Earring_009",
"Earring_010",
"Earring_011",
"Earring_012",
"Earring_013",
"Earring_014",
"Earring_015",
"Earring_016",
"Earring_017",
"Earring_018",
"Earring_Buffer1",
"Earring_Buffer2",
"Earring_Buffer3",
"Earring_Christmas_01",
"Earring_Christmas_02",
"ECelluloseRayon",
"ElastomerFiber",
"EQ_DED_CraneAccessKey",
"EQ_DED_WaterGateKey",
"EQ_HyperCell",
"EQ_IED",
"EQ_SE_PropulsionControlBoard",
"ETC_VendingMachineCoin",
"ExospineCore",
"FaceAccessory_001",
"FaceAccessory_002",
"FaceAccessory_002_Var2",
"FaceAccessory_003",
"FaceAccessory_004",
"FaceAccessory_005",
"FaceAccessory_006",
"FaceAccessory_007",
"FaceAccessory_008",
"FaceAccessory_009",
"FaceAccessory_010",
"FaceAccessory_011",
"FaceAccessory_012",
"FaceAccessory_013",
"FaceAccessory_014",
"FaceAccessory_015",
"FaceAccessory_016",
"FaceAccessory_017",
"FaceAccessory_018",
"FaceAccessory_019",
"FaceAccessory_020",
"FaceAccessory_021",
"FaceAccessory_022",
"FaceAccessory_023",
"FaceAccessory_024",
"FaceAccessory_025",
"FaceAccessory_026",
"FaceAccessory_027",
"FaceAccessory_028",
"FaceAccessory_029",
"FaceAccessory_Buffer1",
"FaceAccessory_Buffer2",
"FaceAccessory_Buffer3",
"FaceAccessory_Christmas_01",
"FaceAccessory_Nier_001",
"Fish_Arowana",
"Fish_Betta",
"Fish_BigeyeBass",
"Fish_BlackRockFish",
"Fish_BlueChromis",
"Fish_Box1",
"Fish_Box2",
"Fish_Box3",
"Fish_Box4",
"Fish_BuffaloFish",
"Fish_ButterflyFish",
"Fish_CannedFish",
"Fish_CannerHam",
"Fish_ChannelCatfish",
"Fish_Dunkleosteus",
"Fish_EmperorAngelfish",
"Fish_FancyCarp",
"Fish_FishCake",
"Fish_FlyingFish",
"Fish_FootBallfish",
"Fish_Goby",
"Fish_GoldFish",
"Fish_GreatWhiteShark",
"Fish_Halibut",
"Fish_LargeMouthBass",
"Fish_Lobster",
"Fish_mackerel",
"Fish_Mahimahi",
"Fish_MolaMola",
"Fish_Mullet",
"Fish_Nikke_Glasses",
"Fish_Nikke_Laplace",
"Fish_Nikke_Poli",
"Fish_Nikke_Rapunzel",
"Fish_Nikke_SnowWhite",
"Fish_Nikke_Tape",
"Fish_NuclearWaste",
"Fish_Pirarucu",
"Fish_PorcupineFish",
"Fish_Rasbora",
"Fish_RedSnapper",
"Fish_SailFish",
"Fish_Salmon",
"Fish_SeaBass",
"Fish_SeaBream",
"Fish_Slice_Bait",
"Fish_Spearfish",
"Fish_Squid",
"Fish_Tire",
"Fish_Triggerfish",
"Fish_Tuna",
"Fish_WhaleShark",
"FishingPoint",
"FishingRod",
"FishingSkillBook1",
"FishingSkillBook2",
"FishingSkillBook3",
"FishingSkillBook4",
"FlashGrenade",
"Gear_AdditiveBetaSkillDamage_Common",
"Gear_AdditiveBetaSkillDamage_Rare",
"Gear_AdditiveBetaSkillDamage_Uncommon",
"Gear_AdditiveBustSkillDamage_Common",
"Gear_AdditiveBustSkillDamage_Rare",
"Gear_AdditiveBustSkillDamage_Uncommon",
"Gear_AdditiveFixedDamage_Common",
"Gear_AdditiveFixedDamage_Rare",
"Gear_AdditiveFixedDamage_Uncommon",
"Gear_AdditiveGiveAndReciveDamageRate_Common",
"Gear_AdditiveGiveAndReciveDamageRate_Rare",
"Gear_AdditiveGiveAndReciveDamageRate_Uncommon",
"Gear_AttackSpeed_Common",
"Gear_AttackSpeed_Rare",
"Gear_AttackSpeed_Uncommon",
"Gear_BetaCrystalAdditiveRate_Common",
"Gear_BetaCrystalAdditiveRate_Rare",
"Gear_BetaCrystalAdditiveRate_Uncommon",
"Gear_BetaGaugeAdditiveRate_Common",
"Gear_BetaGaugeAdditiveRate_Rare",
"Gear_BetaGaugeAdditiveRate_Uncommon",
"Gear_BurstGaugeAdditiveRate_Common",
"Gear_BurstGaugeAdditiveRate_Rare",
"Gear_BurstGaugeAdditiveRate_Uncommon",
"Gear_ComboAttackAdditiveDamage_Common",
"Gear_ComboAttackAdditiveDamage_Rare",
"Gear_ComboAttackAdditiveDamage_Uncommon",
"Gear_CriticalPercentage_Common",
"Gear_CriticalPercentage_Rare",
"Gear_CriticalPercentage_Uncommon",
"Gear_CriticalValueRate_Common",
"Gear_CriticalValueRate_Rare",
"Gear_CriticalValueRate_Uncommon",
"Gear_GainBetaGaugeValueOnDamaged_Common",
"Gear_GainBetaGaugeValueOnDamaged_Rare",
"Gear_GainBetaGaugeValueOnDamaged_Uncommon",
"Gear_GainBurstGaugeValueOnDamaged_Common",
"Gear_GainBurstGaugeValueOnDamaged_Rare",
"Gear_GainBurstGaugeValueOnDamaged_Uncommon",
"Gear_HighHpDamageAdditiveRate_Common",
"Gear_HighHpDamageAdditiveRate_Rare",
"Gear_HighHpDamageAdditiveRate_Uncommon",
"Gear_KillEnemyAdditiveDamageRate_Common",
"Gear_KillEnemyAdditiveDamageRate_Rare",
"Gear_KillEnemyAdditiveDamageRate_Uncommon",
"Gear_KillEnemyHealHP_Common",
"Gear_KillEnemyHealHP_Rare",
"Gear_KillEnemyHealHP_Uncommon",
"Gear_LowHpDamageAdditiveRate_Common",
"Gear_LowHpDamageAdditiveRate_Rare",
"Gear_LowHpDamageAdditiveRate_Uncommon",
"Gear_MaxBurstGauge_Common",
"Gear_MaxBurstGauge_Rare",
"Gear_MaxBurstGauge_Uncommon",
"Gear_MaxShield_Common",
"Gear_MaxShield_Rare",
"Gear_MaxShield_Uncommon",
"Gear_MeleeAttackDamageReductionRate_Common",
"Gear_MeleeAttackDamageReductionRate_Rare",
"Gear_MeleeAttackDamageReductionRate_Uncommon",
"Gear_MeleeRangeDamageReductionRate_Common",
"Gear_MeleeRangeDamageReductionRate_Rare",
"Gear_MeleeRangeDamageReductionRate_Uncommon",
"Gear_RangeAttackDamageAdditiveRate_Common",
"Gear_RangeAttackDamageAdditiveRate_Rare",
"Gear_RangeAttackDamageAdditiveRate_Uncommon",
"Gear_RangeAttackDamageReductionRate_Common",
"Gear_RangeAttackDamageReductionRate_Rare",
"Gear_RangeAttackDamageReductionRate_Uncommon",
"Gear_ShieldAttackPowerRate_Common",
"Gear_ShieldAttackPowerRate_Rare",
"Gear_ShieldAttackPowerRate_Uncommon",
"Gear_ShieldIgnorePercentage_Common",
"Gear_ShieldIgnorePercentage_Rare",
"Gear_ShieldIgnorePercentage_Uncommon",
"Gear_SPExpAdditiveRate_Common",
"Gear_SPExpAdditiveRate_Rare",
"Gear_SPExpAdditiveRate_Uncommon",
"GearCore",
"Hair_000",
"Hair_001",
"Hair_002",
"Hair_003",
"Hair_004",
"Hair_005",
"Hair_006",
"Hair_007",
"Hair_008",
"Hair_009",
"Hair_010",
"Hair_011",
"Hair_012",
"Hair_013",
"Hair_014",
"Hair_015",
"Hair_016",
"Hair_017",
"Hair_018",
"Hair_019",
"Hair_020",
"Hair_021",
"Hair_022",
"Hair_023",
"Hair_024",
"Hair_025",
"Hair_026",
"Hair_027",
"Hair_028",
"Hair_029",
"Hair_030",
"Hair_031",
"Hair_032",
"Hair_033",
"Hair_034",
"Hair_Christmas_01",
"Hair_Nier_001",
"Hair_Nier_002",
"Hair_Nier_003",
"Hair_Nikke_01",
"Hair_Nikke_02",
"Hair_Nikke_03",
"Hair_Nikke_04",
"Hair_Nikke_05",
"Hair_Nikke_06",
"HairMaterial_High",
"HairMaterial_Low",
"HairMaterial_Middle",
"HealGrenade",
"HighDensityWafer",
"HP_Potion",
"HP_Potion_Small",
"HP2Burst_Potion",
"LilyCostume_001",
"LilyCostume_002",
"LilyCostume_003",
"LilyCostume_003_Var2",
"LilyCostume_004",
"LilyCostume_004_Var2",
"LilyCostume_Buffer1",
"LilyCostume_Buffer2",
"LilyCostume_Buffer3",
"LilyCostume_Nier_001",
"LowDensityWafer",
"Lure_Megabait",
"Lure_Weird",
"Money_JunkIron_A",
"Money_JunkIron_B",
"Money_JunkIron_C",
"Money_Nier",
"Money_NightOperation",
"Money_Nikke",
"Nikke_LostAlice",
"Nikke_LostAnis",
"Nikke_LostAR",
"Nikke_LostAssaultRifle",
"Nikke_LostDorothy",
"Nikke_LostModernia",
"Nikke_LostRapi",
"Nikke_PhotomodeSitcker_Dororong",
"PolymerOrganicFilm",
"PT_Burst",
"PT_Combo",
"PT_Crowd",
"PT_Down",
"PT_Grenade",
"PT_Guard",
"PT_Recovery",
"PT_Shoot",
"PT_Skill",
"PT_Stab",
"PT_Survive",
"PT_Tachy",
"PulseGrenade",
"Recovery_HP_Potion",
"ResurrectionName",
"RQ_004_Reward",
"RQ_005_MemoryStick",
"RQ_006_MemoryStick_Amanda",
"RQ_006_MemoryStick_Dona",
"RQ_008_Terminal",
"RQ_010_Bag",
"RQ_018_Potion",
"RQ_021_MemoryStick",
"RQ_AllFishRQ_Reward",
"Shrimp_Bait",
"Special_Bait",
"SPInitializer",
"SQ_006_Token",
"SQ_011_AccessCode_1",
"SQ_011_AccessCode_2",
"SQ_011_AccessCode_3",
"SQ_011_AccessCode_4",
"SQ_011_OmniPlug",
"SQ_020_MemoryStick",
"SQ_020_MemoryStick_Ave",
"SQ_020_MemoryStick_Blake",
"SQ_022_BearDoll",
"SQ_023_FusionCell",
"SQ_024_Wine_1",
"SQ_024_Wine_2",
"SQ_024_Wine_3",
"SQ_027_Book",
"SQ_029_MemoryStick",
"SQ_031_Dryer",
"SQ_031_Scissors",
"SQ_031_Strainer",
"SQ_032_BuddhaStatue",
"SQ_033_MemoryStick_Lee",
"SQ_033_MemoryStick_Woo",
"SQ_033_MemoryStick_Young",
"SQ_034_MemoryStick_Tommy",
"SQ_035_Grape",
"SQ_036_MemoryStick_Go",
"SQ_037_FusionCell",
"SQ_038_MemoryStick_August",
"SQ_038_MemoryStick_July",
"SQ_038_MemoryStick_May",
"SQ_039_MemoryStick",
"SQ_040_MemoryStick_Felix",
"SQ_041_Algorithm_Chipset",
"SQ_042_MemoryStick_Mel",
"SQ_042_MemoryStick_Ran",
"SQ_042_MemoryStick_Rune",
"SQ_042_MemoryStick_Ryu",
"SQ_042_MemoryStick_So",
"SQ_042_MemoryStick_Yo",
"SQ_043_Terminal",
"SQ_Mindmap_Part1",
"SQ_Mindmap_Part2",
"SQ_Mindmap_Part3",
"SQ_Mindmap_Part4",
"SQ_Mindmap_Part5",
"TrapGrenade",
"TumblerCore",
"Weapon_BloodEdge",
"Weapon_RangeMode",
"Weapon_TachyMode",
"WeaponCore",
"WeaponCore_Damaged",
"Worm_Bait",

};


inline const char* ItemNameShow[] =
{
(const char*)u8"极态纳米元素",
(const char*)u8"下水道老鼠",
(const char*)u8"占星师服装",
(const char*)u8"拾荒人",
(const char*)u8"废品回收人",
(const char*)u8"变色龙",
(const char*)u8"夜鹰",
(const char*)u8"清洁工",
(const char*)u8"阔步游人",
(const char*)u8"虚空行者",
(const char*)u8"我不是圣诞老人",
(const char*)u8"艾米尔的头巾",
(const char*)u8"贝塔核心",
(const char*)u8"机体核心",
(const char*)u8"镂空服",
(const char*)u8"占星服",
(const char*)u8"镂空裙装",
(const char*)u8"星球空降服（第2小队）",
(const char*)u8"星球空降服（第2小队）第2版",
(const char*)u8"赛博裙装",
(const char*)u8"赛博服装",
(const char*)u8"休闲针织裙装",
(const char*)u8"舒适针织裙装",
(const char*)u8"星球空降防护服（第7小队）",
(const char*)u8"星球空降防护服（第7小队）第2版",
(const char*)u8"忧郁之雨",
(const char*)u8"奥卡工程师",
(const char*)u8"奥卡技术员",
(const char*)u8"墨黑忍者装",
(const char*)u8"洁白忍者装",
(const char*)u8"洁白忍者装",
(const char*)u8"星球空降服（第7小队）第2版",
(const char*)u8"白礼服",
(const char*)u8"哥特玫瑰",
(const char*)u8"护甲装",
(const char*)u8"活肤紧身服",
(const char*)u8"金色活肤紧身服",
(const char*)u8"黑礼服",
(const char*)u8"休闲吉祥物装",
(const char*)u8"舒适吉祥物装",
(const char*)u8"芍药独韵",
(const char*)u8"绣球花",
(const char*)u8"国色牡丹",
(const char*)u8"乌莲",
(const char*)u8"假日兔",
(const char*)u8"假日兔女郎",
(const char*)u8"假日兔第2版",
(const char*)u8"赛博兔女郎",
(const char*)u8"海洋之丝",
(const char*)u8"黑珍珠",
(const char*)u8"赤色珍珠",
(const char*)u8"碧蓝季风",
(const char*)u8"纯白季风",
(const char*)u8"莹白珍珠",
(const char*)u8"海的女仆",
(const char*)u8"海潮女仆",
(const char*)u8"废料机械师",
(const char*)u8"废品工程师",
(const char*)u8"通勤装",
(const char*)u8"空乘风",
(const char*)u8"拓殖区军校学员",
(const char*)u8"四秒钟”休闲装",
(const char*)u8"冬日星球空降服（第1小队）",
(const char*)u8"星球空降服（第1小队）",
(const char*)u8"冬日星球空降服（第7小队）",
(const char*)u8"空中王牌",
(const char*)u8"天骄王牌",
(const char*)u8"休闲活力装",
(const char*)u8"舒适活力装",
(const char*)u8"四秒钟”破洞牛仔布套装",
(const char*)u8"四秒钟”黑色牛仔布套装",
(const char*)u8"黄色运动服",
(const char*)u8"活力运动服",
(const char*)u8"白色运动服",
(const char*)u8"霓虹运动服",
(const char*)u8"黑玫瑰",
(const char*)u8"玫瑰人生",
(const char*)u8"天使玫瑰",
(const char*)u8"赤血丹心",
(const char*)u8"翡翠热情",
(const char*)u8"白色和平",
(const char*)u8"赛博绑带装",
(const char*)u8"自动绑带装",
(const char*)u8"神经元回路绑带装",
(const char*)u8"赛博绑带装第2版",
(const char*)u8"废土冒险家",
(const char*)u8"废土探索者",
(const char*)u8"动力十足",
(const char*)u8"共鸣",
(const char*)u8"终极兔女郎",
(const char*)u8"赛博魔法师",
(const char*)u8"赛博诡术士",
(const char*)u8"赛博幻术师",
(const char*)u8"狂飙车手",
(const char*)u8"极速快感",
(const char*)u8"女仆",
(const char*)u8"目光焦点",
(const char*)u8"丽影",
(const char*)u8"奥卡探索者",
(const char*)u8"奥卡探路者",
(const char*)u8"神经元链接套装原型",
(const char*)u8"神经元链接套装",
(const char*)u8"神经元链接紧身服",
(const char*)u8"烽火神盾",
(const char*)u8"烽火裙装",
(const char*)u8"盛夏爱丽丝",
(const char*)u8"盛夏小红帽",
(const char*)u8"星球空降服（队长）",
(const char*)u8"毛绒熊熊",
(const char*)u8"粉红小熊",
(const char*)u8"墨色波浪",
(const char*)u8"怒涛",
(const char*)u8"星球空降服（第5小队）",
(const char*)u8"星球空降服（第5小队）第2版",
(const char*)u8"四星物产1号原型",
(const char*)u8"希雍纹服装",
(const char*)u8"希雍纹裙装",
(const char*)u8"希雍科技服",
(const char*)u8"希雍科技裙装",
(const char*)u8"希雍式服装",
(const char*)u8"希雍式裙装",
(const char*)u8"四星物产2号原型",
(const char*)u8"四星物产3号原型",
(const char*)u8"克隆服装",
(const char*)u8"克隆裙装",
(const char*)u8"复刻服装",
(const char*)u8"仿制服装",
(const char*)u8"复刻裙装",
(const char*)u8"仿制裙装",
(const char*)u8"圣诞裙装",
(const char*)u8"星球空降服（第6小队）",
(const char*)u8"星球空降服（第6小队）第2版",
(const char*)u8"星球空降服（第6小队）第3版",
(const char*)u8"牛仔布休闲装",
(const char*)u8"四秒钟”牛仔布套装",
(const char*)u8"星球空降服（第7小队）",
(const char*)u8"休闲车手服",
(const char*)u8"四秒钟”车手服",
(const char*)u8"休闲骑手服",
(const char*)u8"寄叶二号B型制服",
(const char*)u8"寄叶制服1",
(const char*)u8"寄叶非正式礼仪着装",
(const char*)u8"寄叶A型二号制服",
(const char*)u8"浪游剑客服",
(const char*)u8"优雅裙装",
(const char*)u8"极乐净土战斗服",
(const char*)u8"永不回头",
(const char*)u8"遗失之链",
(const char*)u8"冷却服",
(const char*)u8"渡鸦装",
(const char*)u8"神圣护卫套装",
(const char*)u8"休闲水手服",
(const char*)u8"舒适水手服",
(const char*)u8"亮银忍者装",
(const char*)u8"朋克炸街服",
(const char*)u8"朋克风",
(const char*)u8"星球空降服原型",
(const char*)u8"星球空降服（第3小队）",
(const char*)u8"星球空降服（第3小队）第2版",
(const char*)u8"星球空降服原型第2版",
(const char*)u8"贝塔强化剂",
(const char*)u8"高爆弹",
(const char*)u8"飞针",
(const char*)u8"磁轨弹",
(const char*)u8"爆能弹",
(const char*)u8"霰弹",
(const char*)u8"电击弹",
(const char*)u8"弹药包",
(const char*)u8"相机",
(const char*)u8"原味克里欧",
(const char*)u8"克里欧无糖饮料",
(const char*)u8"雪精灵",
(const char*)u8"雪精灵无糖饮料",
(const char*)u8"新地干姜水",
(const char*)u8"无糖新地干姜水",
(const char*)u8"妙之跃",
(const char*)u8"妙之跃无糖饮料",
(const char*)u8"马奇内塔美式咖啡",
(const char*)u8"马奇内塔拿铁咖啡",
(const char*)u8"马奇内塔焦糖玛奇朵",
(const char*)u8"克里欧原味咖啡",
(const char*)u8"克里欧香草咖啡",
(const char*)u8"克里欧抹茶咖啡",
(const char*)u8"庇佑之地伯爵茶",
(const char*)u8"庇佑之地奶茶",
(const char*)u8"庇佑之地绿茶",
(const char*)u8"大麦谷物茶",
(const char*)u8"乌龙谷物茶",
(const char*)u8"玉米谷物茶",
(const char*)u8"橙子甘露",
(const char*)u8"葡萄甘露",
(const char*)u8"苹果甘露",
(const char*)u8"蔓越莓甘露",
(const char*)u8"灵泉胡萝卜汁",
(const char*)u8"灵泉翠汁",
(const char*)u8"红比蒙狮",
(const char*)u8"绿比蒙狮",
(const char*)u8"黑比蒙狮",
(const char*)u8"焰火能量饮料",
(const char*)u8"闪电能量饮料",
(const char*)u8"核子能量饮料",
(const char*)u8"劲能疾风维他命",
(const char*)u8"劲能暴风维他命",
(const char*)u8"劲能冰霜维他命",
(const char*)u8"狄俄倪索斯 - C",
(const char*)u8"月泉水",
(const char*)u8"星泉水",
(const char*)u8"勃朗峰气泡水",
(const char*)u8"珠穆朗玛峰气泡水",
(const char*)u8"汉拿山气泡水",
(const char*)u8"克里欧纯净水",
(const char*)u8"克里欧麦芽酒",
(const char*)u8"巴伐利亚酵母小麦白啤酒",
(const char*)u8"巴伐利亚小麦黑啤酒",
(const char*)u8"海盗拉格啤酒",
(const char*)u8"海盗麦芽啤酒",
(const char*)u8"乔纳森柠檬味嗨棒",
(const char*)u8"乔纳森姜味嗨棒",
(const char*)u8"震荡手雷",
(const char*)u8"设计图：星球空降服（第6小队）",
(const char*)u8"无人机升级模块",
(const char*)u8"战术包",
(const char*)u8"占星师套装",
(const char*)u8"铁甲套装",
(const char*)u8"装甲包",
(const char*)u8"兔宝宝套装",
(const char*)u8"迷你兔套装",
(const char*)u8"毛绒熊熊套装",
(const char*)u8"盖乐世特色套装",
(const char*)u8"希雍纹套装",
(const char*)u8"军团套装",
(const char*)u8"驯鹿鲁道夫套装",
(const char*)u8"辅助机042套装",
(const char*)u8"绯红泪珠",
(const char*)u8"高贵泪珠",
(const char*)u8"点点蓝晶",
(const char*)u8"光点",
(const char*)u8"银齿",
(const char*)u8"金齿",
(const char*)u8"聚变之光",
(const char*)u8"护耳",
(const char*)u8"绿松石环",
(const char*)u8"太阳之泪",
(const char*)u8"记忆耳坠",
(const char*)u8"闪亮记忆",
(const char*)u8"辐射钟摆",
(const char*)u8"黑色矩形",
(const char*)u8"四倍矩形",
(const char*)u8"黄金之心",
(const char*)u8"美玉良珀",
(const char*)u8"水晶之泪",
(const char*)u8"红宝石之泪",
(const char*)u8"摇摆兔兔",
(const char*)u8"黄金枝",
(const char*)u8"承传标记",
(const char*)u8"盖乐世严选",
(const char*)u8"母主之触",
(const char*)u8"高贵耳饰",
(const char*)u8"花环耳饰",
(const char*)u8"雪橇耳夹",
(const char*)u8"极态聚合物材料",
(const char*)u8"聚合物材料",
(const char*)u8"起重机ID卡",
(const char*)u8"水闸钥匙",
(const char*)u8"超能电池",
(const char*)u8"聚变电池",
(const char*)u8"推进装置控制面板",
(const char*)u8"维特币",
(const char*)u8"万用卡",
(const char*)u8"椭圆角质架眼镜",
(const char*)u8"大圆框眼镜",
(const char*)u8"超大圆框眼镜",
(const char*)u8"经典圆框眼镜",
(const char*)u8"棕色角质架眼镜",
(const char*)u8"金属框架眼镜",
(const char*)u8"猫眼",
(const char*)u8"实验室护目镜",
(const char*)u8"超窄太阳镜",
(const char*)u8"橙色飞行员太阳镜",
(const char*)u8"多边形方框眼镜",
(const char*)u8"方框眼镜",
(const char*)u8"半框眼镜",
(const char*)u8"超大号太阳镜",
(const char*)u8"赤红面具",
(const char*)u8"翡绿面具",
(const char*)u8"蜂巢面具",
(const char*)u8"红白面具",
(const char*)u8"竞速面具",
(const char*)u8"拼接面具",
(const char*)u8"黑色面具",
(const char*)u8"毒物面具",
(const char*)u8"金色面具",
(const char*)u8"绯红面具",
(const char*)u8"蚱蜢面具",
(const char*)u8"铁制面具",
(const char*)u8"环绕式太阳镜",
(const char*)u8"漩涡眼镜",
(const char*)u8"眼罩",
(const char*)u8"偏光太阳镜",
(const char*)u8"盖乐世眼镜",
(const char*)u8"高贵光学眼镜",
(const char*)u8"希雍科技眼镜",
(const char*)u8"冰晶眼镜",
(const char*)u8"战斗护目饰",
(const char*)u8"金龙鱼",
(const char*)u8"斗鱼",
(const char*)u8"大眼鲈鱼",
(const char*)u8"眼张鱼",
(const char*)u8"燕尾蓝魔",
(const char*)u8"花哨的箱子",
(const char*)u8"坚固的箱子",
(const char*)u8"普通的箱子",
(const char*)u8"破旧的箱子",
(const char*)u8"隆头鹦嘴鱼",
(const char*)u8"蝴蝶鱼",
(const char*)u8"鱼罐头",
(const char*)u8"罐头火腿",
(const char*)u8"钳鱼",
(const char*)u8"邓氏鱼",
(const char*)u8"主刺盖鱼",
(const char*)u8"锦鲤",
(const char*)u8"鱼饼",
(const char*)u8"飞鱼",
(const char*)u8"灯笼鱼",
(const char*)u8"弹涂鱼",
(const char*)u8"金鱼",
(const char*)u8"大白鲨",
(const char*)u8"大比目鱼",
(const char*)u8"大口黑鲈",
(const char*)u8"龙虾",
(const char*)u8"鲭鱼",
(const char*)u8"鬼头刀",
(const char*)u8"翻车鱼",
(const char*)u8"鲻鱼",
(const char*)u8"尼恩的眼镜",
(const char*)u8"拉普拉斯",
(const char*)u8"波莉",
(const char*)u8"长发公主",
(const char*)u8"白雪公主",
(const char*)u8"卡式录音带",
(const char*)u8"核废料",
(const char*)u8"巨骨舌鱼",
(const char*)u8"刺豚",
(const char*)u8"波鱼",
(const char*)u8"红鲷鱼",
(const char*)u8"平鳍旗鱼",
(const char*)u8"鲑鱼",
(const char*)u8"海鲈鱼",
(const char*)u8"真鲷",
(const char*)u8"鱼片",
(const char*)u8"锯鳞四鳍旗鱼",
(const char*)u8"鱿鱼",
(const char*)u8"轮胎",
(const char*)u8"扳机鱼",
(const char*)u8"太平洋蓝鳍金枪鱼",
(const char*)u8"鲸鲨",
(const char*)u8"钓鱼积分",
(const char*)u8"钓鱼竿",
(const char*)u8"钓鱼数据",
(const char*)u8"进阶钓鱼数据",
(const char*)u8"神奇钓鱼数据",
(const char*)u8"最佳钓鱼数据",
(const char*)u8"声波手雷",
(const char*)u8"贝塔增强组件",
(const char*)u8"贝塔增强组件",
(const char*)u8"贝塔增强组件",
(const char*)u8"爆发增强组件",
(const char*)u8"爆发增强组件",
(const char*)u8"爆发增强组件",
(const char*)u8"固定伤害组件",
(const char*)u8"固定伤害组件",
(const char*)u8"固定伤害组件",
(const char*)u8"双刃组件",
(const char*)u8"双刃组件",
(const char*)u8"双刃组件",
(const char*)u8"加速组件",
(const char*)u8"加速组件",
(const char*)u8"加速组件",
(const char*)u8"金方组件",
(const char*)u8"金方组件",
(const char*)u8"金方组件",
(const char*)u8"贝塔充能组件",
(const char*)u8"贝塔充能组件",
(const char*)u8"贝塔充能组件",
(const char*)u8"爆发充能组件",
(const char*)u8"爆发充能组件",
(const char*)u8"爆发充能组件",
(const char*)u8"组合连击增强组件",
(const char*)u8"组合连击增强组件",
(const char*)u8"组合连击增强组件",
(const char*)u8"暴击强化组件",
(const char*)u8"暴击强化组件",
(const char*)u8"暴击强化组件",
(const char*)u8"暴击伤害增强组件",
(const char*)u8"暴击伤害增强组件",
(const char*)u8"暴击伤害增强组件",
(const char*)u8"贝塔恢复组件",
(const char*)u8"贝塔恢复组件",
(const char*)u8"贝塔恢复组件",
(const char*)u8"爆发恢复组件",
(const char*)u8"爆发恢复组件",
(const char*)u8"爆发恢复组件",
(const char*)u8"完美战斗组件",
(const char*)u8"完美战斗组件",
(const char*)u8"完美战斗组件",
(const char*)u8"战斗延续组件",
(const char*)u8"战斗延续组件",
(const char*)u8"战斗延续组件",
(const char*)u8"战斗补给组件",
(const char*)u8"战斗补给组件",
(const char*)u8"战斗补给组件",
(const char*)u8"背水一战组件",
(const char*)u8"背水一战组件",
(const char*)u8"背水一战组件",
(const char*)u8"爆发拓展组件",
(const char*)u8"爆发拓展组件",
(const char*)u8"爆发拓展组件",
(const char*)u8"护盾增强组件",
(const char*)u8"护盾增强组件",
(const char*)u8"护盾增强组件",
(const char*)u8"近战防护组件",
(const char*)u8"近战防护组件",
(const char*)u8"近战防护组件",
(const char*)u8"防护组件",
(const char*)u8"防护组件",
(const char*)u8"防护组件",
(const char*)u8"远程增强组件",
(const char*)u8"远程增强组件",
(const char*)u8"远程增强组件",
(const char*)u8"远程防护组件",
(const char*)u8"远程防护组件",
(const char*)u8"远程防护组件",
(const char*)u8"护盾伤害组件",
(const char*)u8"护盾伤害组件",
(const char*)u8"护盾伤害组件",
(const char*)u8"护盾穿透组件",
(const char*)u8"护盾穿透组件",
(const char*)u8"护盾穿透组件",
(const char*)u8"训练组件",
(const char*)u8"训练组件",
(const char*)u8"训练组件",
(const char*)u8"万用螺栓",
(const char*)u8"星球空降马尾",
(const char*)u8"卡西姆的抉择",
(const char*)u8"最可爱的发型",
(const char*)u8"希雍公主",
(const char*)u8"桃香",
(const char*)u8"哥特时代",
(const char*)u8"女儿的回忆",
(const char*)u8"初恋",
(const char*)u8"武士刀",
(const char*)u8"情人节",
(const char*)u8"卡西姆的招牌发型",
(const char*)u8"假日",
(const char*)u8"创新之作",
(const char*)u8"宁静",
(const char*)u8"象征主义",
(const char*)u8"革新",
(const char*)u8"冷冻酸奶",
(const char*)u8"鸣鸟",
(const char*)u8"小女巫",
(const char*)u8"卡西姆的艺术",
(const char*)u8"生命万岁",
(const char*)u8"含羞草之花",
(const char*)u8"希雍之梦",
(const char*)u8"摩登天使",
(const char*)u8"喵~",
(const char*)u8"机甲兔兔",
(const char*)u8"飞萤",
(const char*)u8"18号",
(const char*)u8"春日芬芳",
(const char*)u8"冬日芬芳",
(const char*)u8"夏日芬芳",
(const char*)u8"天使旋舞",
(const char*)u8"胜利女神",
(const char*)u8"隐藏真心",
(const char*)u8"9号幽灵",
(const char*)u8"圣诞女孩",
(const char*)u8"寄叶二号B型发型",
(const char*)u8"白狐面具发型",
(const char*)u8"寄叶A型二号发型",
(const char*)u8"月下美人",
(const char*)u8"高贵典雅",
(const char*)u8"标准长发",
(const char*)u8"活力刘海",
(const char*)u8"初恋",
(const char*)u8"潮流双马尾",
(const char*)u8"精油材料",
(const char*)u8"纤维材料",
(const char*)u8"色度材料",
(const char*)u8"生化力场发生器",
(const char*)u8"先进纳米元素",
(const char*)u8"高浓度药水",
(const char*)u8"长效药水",
(const char*)u8"爆发强化剂",
(const char*)u8"阿尔忒弥斯",
(const char*)u8"占星师外套",
(const char*)u8"忧郁之雨",
(const char*)u8"雨天",
(const char*)u8"休假日",
(const char*)u8"休息日",
(const char*)u8"黛安娜",
(const char*)u8"进化",
(const char*)u8"百合·阿尔忒弥斯制作的服装",
(const char*)u8"寄叶九号S型制服",
(const char*)u8"纳米元素",
(const char*)u8"神奇鱼饵",
(const char*)u8"奇怪的鱼饵",
(const char*)u8"微型驱动装置",
(const char*)u8"微型马达",
(const char*)u8"微型线圈",
(const char*)u8"星之泪",
(const char*)u8"贝塔种子",
(const char*)u8"骨头扳手",
(const char*)u8"兔子玩偶",
(const char*)u8"罐装气泡水",
(const char*)u8"军品",
(const char*)u8"军品",
(const char*)u8"桃乐丝的遮阳伞",
(const char*)u8"指挥官人偶",
(const char*)u8"拉毗的帽子",
(const char*)u8"神秘生物贴纸",
(const char*)u8"先进聚合物材料",
(const char*)u8"爆发出神”型辅助脊椎",
(const char*)u8"连锁反应”型辅助脊椎",
(const char*)u8"强力冲击”型辅助脊椎",
(const char*)u8"碾压”型辅助脊椎",
(const char*)u8"掷弹兵”型辅助脊椎",
(const char*)u8"本能反应”型辅助脊椎",
(const char*)u8"恢复”型辅助脊椎",
(const char*)u8"鹰眼”型辅助脊椎",
(const char*)u8"贝塔出神”型辅助脊椎",
(const char*)u8"伪装”型辅助脊椎",
(const char*)u8"防护”型辅助脊椎",
(const char*)u8"审判”型辅助脊椎",
(const char*)u8"脉冲手雷",
(const char*)u8"可续用维生包",
(const char*)u8"白血泵",
(const char*)u8"算术女王徽章",
(const char*)u8"马修的记忆棒",
(const char*)u8"阿曼达的记忆棒",
(const char*)u8"唐娜的记忆棒",
(const char*)u8"设备HM021",
(const char*)u8"弗兰克的旅行袋",
(const char*)u8"沙疫治疗药品",
(const char*)u8"亚伦的记忆棒",
(const char*)u8"传说之鱼徽章",
(const char*)u8"虾米",
(const char*)u8"特殊鱼饵",
(const char*)u8"技能点初始化设备",
(const char*)u8"入场凭证",
(const char*)u8"母网访问码",
(const char*)u8"母网访问码",
(const char*)u8"母网访问码",
(const char*)u8"母网访问码",
(const char*)u8"万用插头",
(const char*)u8"战友的记忆棒",
(const char*)u8"阿贝的记忆棒",
(const char*)u8"布莱克的记忆棒",
(const char*)u8"泰迪熊",
(const char*)u8"有凹损的聚变电池",
(const char*)u8"慕拉酒庄葡萄酒",
(const char*)u8"雅克杜尔内葡萄酒",
(const char*)u8"纳帕朗提葡萄酒",
(const char*)u8"《信仰之书》",
(const char*)u8"爱人的记忆棒",
(const char*)u8"吹风机",
(const char*)u8"剪刀",
(const char*)u8"直发夹",
(const char*)u8"鎏金青铜立佛",
(const char*)u8"李的记忆棒",
(const char*)u8"吴的记忆棒",
(const char*)u8"杨的记忆棒",
(const char*)u8"汤米的记忆棒",
(const char*)u8"葡萄",
(const char*)u8"高的记忆棒",
(const char*)u8"老式聚变电池",
(const char*)u8"奥古斯特的记忆棒",
(const char*)u8"朱莱的记忆棒",
(const char*)u8"梅的记忆棒",
(const char*)u8"埃科的记忆棒",
(const char*)u8"菲利克斯的记忆棒",
(const char*)u8"算法芯片组",
(const char*)u8"米尔的记忆棒",
(const char*)u8"拉安的记忆棒",
(const char*)u8"鲁恩的记忆棒",
(const char*)u8"柳的记忆棒",
(const char*)u8"徐的记忆棒",
(const char*)u8"姚的记忆棒",
(const char*)u8"受损的设备",
(const char*)u8"思维导图副本",
(const char*)u8"思维导图副本",
(const char*)u8"思维导图副本",
(const char*)u8"思维导图副本",
(const char*)u8"思维导图副本",
(const char*)u8"智能地雷",
(const char*)u8"维生包拓展模块",
(const char*)u8"血刃",
(const char*)u8"阿尔忒弥斯加农炮",
(const char*)u8"迅子光刃",
(const char*)u8"武器核心",
(const char*)u8"受损的武器核心",
(const char*)u8"蠕动的虫子"
};

