inline const char* AllPlayerActionModeName[] =
{
	"Groggy",
	"DownFaceUp",
	"DownFaceUp_E",
	"DownFaceDown",
	"DownFaceDown_E",
	"KnockBack",
	"KnockBackStrong",
	"KnockDownForward_Eve",
	"KnockDownForwardTumbling_Eve",
	"KnockDownForward_NoMove",
	"KnockDownBackward_Eve",
	"KnockDownBackwardTumbling_Eve",
	"KnockDownBackward_NoMove",
	"KnockDownTumbling_Eve_EffectArea",
	"KnockDownBackward_Link2",
	"WallHit",
	"HitAirForward_Eve",
	"HitAirForwardFall_Eve",
	"HitAirForwardEnd_Eve",
	"HitAirForwardDown_Eve",
	"HitAirBackward_Eve",
	"HitAirBackwardFall_Eve",
	"HitAirBackwardEnd_Eve",
	"HitAirBackwardDown_Eve",
	"BreakFall_Ready",
	"P_Eve_Skill_KnockDown_NoMove",
	"HitImpactTiny",
	"HitImpactLight",
	"HitImpactLightLink",
	"HitImpactStrong",
	"HitImpactStrongLink",
	"HitImpactStrongLink_NoSound",
	"HitImpactHeavy",
	"HitImpactSlash_Light",
	"HitImpactSlash_Strong",
	"HitImpactPierce_Light",
	"HitImpactPierce_Strong",
	"HitImpactBlunt_Light",
	"HitImpactBlunt_Strong",
	"HitImpactProjectile",
	"HitImpactTiny_Poison",
	"HitImpactTiny_Explosion",
	"LV_Damage_Barrel01_Show",
	"P_EVE_LevelAction_Stumble_01",
	"LV_Stealth_End_Screeneffect",
	"LV_Stealth_End_StealthIcon",
	"LV_Warp",
	"LV_EM_Bar_TypeB_Disable_Falling_Start",
	"LV_EM_Bar_TypeB_Disable_Falling_Loop",
	"LV_Damage_Barrel02_Show",
	"LV_FallDownEV_CrashInner_Show",
	"LV_FallDownEV_CrashOuter_Show",
	"LV_TrapTypeA",
	"LV_FinishQTE_FailDown_Crawler",
	"T_LV_BlockAction",
	"T_CircleWaveArea_Damage",
	"T_ClriketCGrab_TryLinkBreak",
	"T_BoneShakeAnim",
	"Airborne",
	"AirborneDown",
	"T_RollKnockBack",
	"T_Eve_GravityPull",
	"Falling_Dead_Show_Effect",
	"M_DroidOld_ParryToEVE",
	"M_DroidOld_DashSlow_SkillDamage",
	"M_BodyBag_SuicideBomb_DamageEve",
	"M_LabMutant_GrabSudden_HitL",
	"M_Mann_KnockDownForward",
	"M_Mann_KnockDownForward_NoMove",
	"M_Mann_DashSwing_HitE1",
	"M_Mann_Grab_HitL1",
	"M_Mann_Grab_HitL2",
	"M_LurkerA_Grab_HitL",
	"M_Behemoth_HeadButtCombo2_HitL"
};


inline const char* AllPlayerActionModeNameShow[] =
{
	(const char*)u8"果子定身",
	(const char*)u8"摔倒脸朝上（1）",
	(const char*)u8"摔倒脸朝上（2）",
	(const char*)u8"摔倒脸朝下（1）",
	(const char*)u8"摔倒脸朝下（2）",
	(const char*)u8"被击退",
	(const char*)u8"被强力击退",
	(const char*)u8"前翻摔倒（1）",
	(const char*)u8"前翻摔倒（2）",
	(const char*)u8"原地前翻摔倒",
	(const char*)u8"后翻摔倒（1）",
	(const char*)u8"后翻摔倒（2）",
	(const char*)u8"原地前翻摔倒",
	(const char*)u8"翻滚",
	(const char*)u8"大后翻滚",
	(const char*)u8"眩晕撞击",
	(const char*)u8"空中前进（后退）",
	(const char*)u8"空中前进（坠落）",
	(const char*)u8"空中前进（结束）",
	(const char*)u8"空中前进（倒地）",
	(const char*)u8"空中向后（后退）",
	(const char*)u8"空中向后（坠落）",
	(const char*)u8"空中向后（结束）",
	(const char*)u8"空中向后（倒地）",
	(const char*)u8"前速微翻滚",
	(const char*)u8"被原地击倒",
	(const char*)u8"小撞击",
	(const char*)u8"中等受伤",
	(const char*)u8"中等受伤（无特效声音）",
	(const char*)u8"强力受伤",
	(const char*)u8"强力受伤（无特效声音）",
	(const char*)u8"强力受伤（无声音）",
	(const char*)u8"重撞击",
	(const char*)u8"中等切割受伤",
	(const char*)u8"强力切割受伤",
	(const char*)u8"中等刺击受伤",
	(const char*)u8"强力刺击受伤",
	(const char*)u8"中等钝器受伤",
	(const char*)u8"强力钝器受伤",
	(const char*)u8"弹丸受伤",
	(const char*)u8"中毒受伤",
	(const char*)u8"爆炸受伤",
	(const char*)u8"受击后退",
	(const char*)u8"动作失误",
	(const char*)u8"隐身束屏幕效果",
	(const char*)u8"隐身图标",
	(const char*)u8"扭曲",
	(const char*)u8"倒地（会浮空）",
	(const char*)u8"倒地（挣扎）",
	(const char*)u8"受击后移",
	(const char*)u8"下落碰撞外部",
	(const char*)u8"下落碰撞内部",
	(const char*)u8"踩住陷阱A",
	(const char*)u8"未完成QTE倒地",
	(const char*)u8"格挡动作",
	(const char*)u8"圆波受伤",
	(const char*)u8"尝试中断链接（只有声音）",
	(const char*)u8"骨摇动漫（飙血）",
	(const char*)u8"空中翻滚",
	(const char*)u8"空中翻滚下坠",
	(const char*)u8"滚动",
	(const char*)u8"拉力",
	(const char*)u8"死亡回音",
	(const char*)u8"招架至击",
	(const char*)u8"短跑慢技能伤害",
	(const char*)u8"自杀炸弹伤害受击",
	(const char*)u8"受到突变体突然攻击",
	(const char*)u8"后翻脸着地",
	(const char*)u8"原地翻滚脸着地",
	(const char*)u8"冲击摆动受击",
	(const char*)u8"后翻击",
	(const char*)u8"原地后翻击",
	(const char*)u8"被击倒在地",
	(const char*)u8"巨兽头槌受击",
};


inline const char* AllPlayerHitModeName[] =
{
	"LV_DOT_HPRate5",
	"LV_FireZone_Damage",
	"LV_FireZone_DamageZone",
	"LV_Damage_Door01",
	"LV_Damage_SlopeActor_01",
	"LV_Damage_SlopeActor_02",
	"LV_Damage_SlopeActor_03",
	"LV_Damage_Barrel02",
	"LV_Damage_Barrel01_Flint",
	"LV_LaserDotdamage01",
	"LV_LaserDotdamage02",
	"LV_Damage_Dronebomb",
	"LV_LaserDamage_PC_Dead",
	"M_TurretLaser_Laser_Projectile1_ExplosionArea"
};

inline const char* AllPlayerHitModeNameShow[] =
{
	(const char*)u8"循环扣血直到死亡",
	(const char*)u8"单次受击扣血",
	(const char*)u8"单次受击扣血直到死亡",
	(const char*)u8"受伤（门？？）",
	(const char*)u8"受击（不平稳版本1 ）",
	(const char*)u8"受击（不平稳版本2 ）",
	(const char*)u8"受击（原地翻滚 ）",
	(const char*)u8"受击（秒一管血，不开无限血量和不朽会直接死亡）",
	(const char*)u8"受击（火石？？）",
	(const char*)u8"受击（激光损伤）",
	(const char*)u8"受击（秒死，无论你是否开启无限血量，无敌或者不朽都会直接死亡，属于脚本事件）",
	(const char*)u8"受击（炸弹）",
	(const char*)u8"受击（激光损伤，秒死）",
	(const char*)u8"子弹击倒",
};

inline const char* AllPlayerSpecialEffectsName[] =
{
	"Show_ResultHitWeakPoint",
	"P_Eve_CounterSkillSignal",
	"ShockSlugStun",
	"M_Common_Rage",
	"T_Common_WarpSmall",
	"T_Common_WarpLarge",
	"M_BodyBag_SuicideBomb_DamageArea",
	"M_Maelstrom_Spit_Projectile1_ArriveArea",
	"M_Maelstrom_SpitMulti_Projectile1_ArriveArea",
	"M_Maelstrom_AYL_WeakPointOpen1",
	"M_Maelstrom_AYL_WeakPointBreak1",
	"M_GrubShooterEliteB_SpitMassAttack_1_Projectile1_ExplosionArea",
	"M_GrubShooterEliteB_SpitDozenAttack_1_Projectile1_ExplosionArea",
	"M_Mann_ThrowShot_Projectile_ExplosionReady",
	"M_Mann_WideSlash_ExplosionReady",
	"P_Eve_GunNikke_HealEvent",
	"M_DroidTurret_Nikke_ShotDebuff_Projectile1_HitZoneArea",
	"M_Maelstrom_Nikke_ExplosionArea_Ready",
	"N_Dummy_BeachExplosion_Signal",
	"N_Dummy_BeachExplosion_Start1",
	"N_Dummy_BeachExplosionFront_Start",
	"N_Dummy_BeachExplosionBack_Start",
	"N_Dummy_ExplosionWLB_Start",
	"N_Dummy_ExplosionWLB_Signal",
	"M_Gardener_SingleShot_1_Projectile1_ExplosionArea",
	"M_Gardener_SingleShot_1_Projectile1_PoisonZoneArea",
	"M_GrubDash_JustParry",
	"M_GrubShooterElite_SpitMassAttack_1_Projectile1_ExplosionArea",
	"M_GrubShooterElite_SpitDozenAttack_1_Projectile1_ExplosionArea",
	"M_Crawler_PlasmaMine_HitArea1",
	"M_Crawler_LightningSmash_HitArea1",
	"M_HedgeBoarBrute_RangeExplosion_HitArea1",
	"M_Behemoth_Parry_HitE",
	"M_ExoSuit_EnergyBomb_Projectile_ExplosionReady",
	"M_ExoSuit_EnergyBombBig_Projectile_ExplosionReady",
	"M_ExoSuit_AreaBomb_Projectile_ExplosionReady",
	"M_BotRange_Nikke_Missile_ExplosionFX",
	"M_Behemoth_Nikke_TornadoShot_Projectile1_TornadoZoneArea",
	"M_Behemoth_Nikke_WeakPointGroggy",
	"M_BotAttacker_Nikke_Missile_ExplosionFX",
	"M_BotAttacker_Nikke_WeakPointAllBreak",
	"P_Eve_InteractCamp_RestFX",
	"Item_Buff_ShieldAttack50",
	"Test_Nikke_EnterStage_ScreenEffect_Show",
};

inline const char* AllPlayerSpecialEffectsNameShow[] =
{
	(const char*)u8"脚坏果子",
	(const char*)u8"反技能信号",
	(const char*)u8"玩家电击",
	(const char*)u8"愤怒",
	(const char*)u8"小光",
	(const char*)u8"中光",
	(const char*)u8"自杀炸弹伤害破坏效果（火焰燃烧）",
	(const char*)u8"爆炸投掷物特效（大）",
	(const char*)u8"爆炸投掷物特效（小）",
	(const char*)u8"果子特效（无法消失，死亡或使用下面的眩晕无果子破坏它）",
	(const char*)u8"眩晕无果子（如果果子特效生成了很多，点一次是无法破坏全部的）",
	(const char*)u8"喷火式大规模攻击弹爆炸特效",
	(const char*)u8"喷火式大规模攻击弹粒子特效",
	(const char*)u8"霰弹爆炸特效",
	(const char*)u8"火焰喷发",
	(const char*)u8"回血特效（也会回血）",
	(const char*)u8"毛刺弹特效",
	(const char*)u8"旋涡爆炸特效",
	(const char*)u8"天降陨石（本人位置）",
	(const char*)u8"天降陨石（附近随机位置）",
	(const char*)u8"天降陨石（面前）",
	(const char*)u8"天降陨石（背后）",
	(const char*)u8"天降电击（附近随机位置）",
	(const char*)u8"天降电击（本人位置）",
	(const char*)u8"投射物爆炸特效",
	(const char*)u8"投射物粒子特效",
	(const char*)u8"招架特效（会导致后退）",
	(const char*)u8"攻击弹爆炸特效（绿色）",
	(const char*)u8"攻击弹粒子特效（绿色）",
	(const char*)u8"升华特效",
	(const char*)u8"升华特效（一行）",
	(const char*)u8"火焰爆炸",
	(const char*)u8"摔地（人物会摔倒）",
	(const char*)u8"能量炸弹爆炸",
	(const char*)u8"能量炸弹爆炸（大）",
	(const char*)u8"能量炸弹爆炸（巨型，可以对怪造成伤害，清空附近的怪）",
	(const char*)u8"机器人导弹爆炸",
	(const char*)u8"狂风爆炸特效",
	(const char*)u8"狂风眩晕特效",
	(const char*)u8"机器人攻击炸弹爆炸",
	(const char*)u8"机器人爆炸眩晕",
	(const char*)u8"休息特效",
	(const char*)u8"护盾Buff特效",
	(const char*)u8"穿梭特效（注意：会卡黑屏，自杀解决）",
};